services:
  db:
    image: postgres:15
    container_name: odoo_steg_db
    environment:
      - POSTGRES_DB=steg_stock
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=steg_odoo_2024
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d steg_stock"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo_steg_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=steg_odoo_2024
      - PGPASSWORD=steg_odoo_2024
    volumes:
      # Configuration
      - ./config:/etc/odoo
      # Modules personnalisés
      - ./custom_addons:/mnt/extra-addons
      # Données
      - odoo-web-data:/var/lib/odoo
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data: